name: Sync single database

on: workflow_dispatch

permissions: write-all

jobs:
  Easy:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_ez.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Easy
          path: |
            data/runtime/*

  Fabric:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_fabric.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Fabric
          path: |
            data/runtime/*

  Forge:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_forge.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Forge
          path: |
            data/runtime/*

  PaperMC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_papermc.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: PaperMC
          path: |
            data/runtime/*

  LeavesMC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_leavesmc.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: LeavesMC
          path: |
            data/runtime/*

  MohistMC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_mohistmc.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: MohistMC
          path: |
            data/runtime/*

  PurpurMC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Sync Database
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U -r requirements.txt
          python main.py -i
          python main_purpurmc.py -u

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: PurpurMC
          path: |
            data/runtime/*
